const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94750122621"
const SESSION_ID = "PRABATH-MD~eV0GVRYY#jzHnjT7q3h1IMY_Xzd32qd0ydkNRqh7ejSFZk_Tr3X4"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
