name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      SESSION_ID: PRABATH-MD~QqV2ET4S#HAjxf_lXD2vouhtO84vfIot2HfvArhD_eo5eSq2PGUk
      GITHUB_AUTH_TOKEN: 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
      BOT_NUMBER: 94750122621

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Start application
      run: npm start
